apiVersion: v1
kind: Service
metadata:
  name: tetrahedron-backend
spec:
  selector:
    app: tetrahedron-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
