apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetrahedron-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tetrahedron-frontend
  template:
    metadata:
      labels:
        app: tetrahedron-frontend
    spec:
      containers:
        - name: tetrahedron-frontend
          image: your-dockerhub-username/tetrahedron-frontend:latest
          ports:
            - containerPort: 80
