name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11 for Backend
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build Backend with Gradle
        run: ./gradlew build
        working-directory: ./backend

      - name: Build and Push Backend Docker image
        run: |
          docker build -t your-dockerhub-username/tetrahedron-backend:latest ./backend
          docker push your-dockerhub-username/tetrahedron-backend:latest

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build Frontend
        run: npm install && npm run build
        working-directory: ./frontend

      - name: Build and Push Frontend Docker image
        run: |
          docker build -t your-dockerhub-username/tetrahedron-frontend:latest ./frontend
          docker push your-dockerhub-username/tetrahedron-frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          aws eks --region your-aws-region update-kubeconfig --name your-eks-cluster-name

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./k8s/mongo-deployment.yaml
          kubectl apply -f ./k8s/mongo-service.yaml
          kubectl apply -f ./k8s/backend-deployment.yaml
          kubectl apply -f ./k8s/backend-service.yaml
          kubectl apply -f ./k8s/frontend-deployment.yaml
          kubectl apply -f ./k8s/frontend-service.yaml
